import { useState, useEffect, useRef } from 'react'
import { createPortal } from 'react-dom'
import { api } from '../api'

const PRIORITIES = ['All', 'Low', 'Medium', 'High', 'Critical']
const STATUSES = ['New', 'Reviewed', 'In Progress', 'Done', 'Future Consideration']

const PRIORITY_COLORS = {
  Low: 'bg-gray-500/20 text-gray-300 border-gray-500/30',
  Medium: 'bg-yellow-500/20 text-yellow-300 border-yellow-500/30',
  High: 'bg-orange-500/20 text-orange-300 border-orange-500/30',
  Critical: 'bg-red-500/20 text-red-300 border-red-500/30',
}

const STATUS_COLORS = {
  New: 'bg-[var(--color-primary-500)]/20 text-[var(--color-primary-300)] border-[var(--color-primary-500)]/30',
  Reviewed: 'bg-blue-500/20 text-blue-300 border-blue-500/30',
  'In Progress': 'bg-purple-500/20 text-purple-300 border-purple-500/30',
  Done: 'bg-green-500/20 text-green-300 border-green-500/30',
  'Future Consideration': 'bg-purple-500/20 text-purple-300 border-purple-500/30',
}

function formatDate(ts) {
  if (!ts) return ''
  return new Date(ts).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric', hour: '2-digit', minute: '2-digit' })
}

function sourceIcon(source) {
  if (!source) return null
  const s = source.toLowerCase()
  if (s.includes('meeting')) return '🎙️'
  return '📝'
}

export default function Backlog() {
  const [items, setItems] = useState([])
  const [employees, setEmployees] = useState([])
  const [loading, setLoading] = useState(true)
  const [submitting, setSubmitting] = useState(false)
  const [showAdd, setShowAdd] = useState(false)
  const [notification, setNotification] = useState(null)
  const [search, setSearch] = useState('')
  const [priorityFilter, setPriorityFilter] = useState('All')
  const [statusFilter, setStatusFilter] = useState('All')
  const [suggestions, setSuggestions] = useState([])
  const [scanning, setScanning] = useState(false)
  const [generating, setGenerating] = useState(false)
  const [showAiGenerate, setShowAiGenerate] = useState(false)
  const [aiPrompt, setAiPrompt] = useState('')
  const [selectedImage, setSelectedImage] = useState(null)
  const [detailItem, setDetailItem] = useState(null)
  const [showCustomScan, setShowCustomScan] = useState(false)
  const [customScanDate, setCustomScanDate] = useState('')
  const [page, setPage] = useState(1)
  const [tab, setTab] = useState('all') // 'pending' | 'converted' | 'all'
  const [convertingId, setConvertingId] = useState(null)
  const perPage = 10
  const fileInputRef = useRef(null)

  const [form, setForm] = useState({
    description: '',
    priority: 'Medium',
    owner: '',
    status: 'New',
    image_data: '',
    image_name: '',
  })

  useEffect(() => {
    Promise.all([
      api.getBacklogItems().then(data => {
        const arr = Array.isArray(data) ? data : data.results || []
        setItems(arr)
      }).catch(() => {
        showNotif('Failed to load backlog items', 'error')
      }),
      api.getEmployees().then(data => {
        setEmployees(data)
      }).catch(() => {}),
    ]).finally(() => setLoading(false))
  }, [])

  useEffect(() => {
    if (!loading) handleScan(false, 1)
  }, [loading])

  // Lock body scroll when any modal is open (same pattern as Tasks page)
  useEffect(() => {
    const modalOpen = detailItem || showAdd || showAiGenerate
    const main = document.querySelector('main')
    if (modalOpen) {
      document.body.style.overflow = 'hidden'
      document.documentElement.style.overflow = 'hidden'
      if (main) main.style.overflow = 'hidden'
    } else {
      document.body.style.overflow = ''
      document.documentElement.style.overflow = ''
      if (main) main.style.overflow = ''
    }
    return () => {
      document.body.style.overflow = ''
      document.documentElement.style.overflow = ''
      if (main) main.style.overflow = ''
    }
  }, [detailItem, showAdd, showAiGenerate])

  const showNotif = (message, type = 'success') => {
    setNotification({ message, type })
    setTimeout(() => setNotification(null), 4000)
  }

  const handleImageSelect = (e) => {
    const file = e.target.files?.[0]
    if (!file) return
    if (file.size > 5 * 1024 * 1024) {
      showNotif('Image must be under 5MB', 'error')
      return
    }
    const reader = new FileReader()
    reader.onload = (ev) => {
      setForm(prev => ({ ...prev, image_data: ev.target.result, image_name: file.name }))
    }
    reader.readAsDataURL(file)
  }

  const handleAiGenerate = async () => {
    if (!aiPrompt.trim()) {
      showNotif('Please enter a prompt', 'error')
      return
    }
    setGenerating(true)
    try {
      const created = await api.generateBacklogFromPrompt(aiPrompt.trim())
      setItems(prev => [created, ...prev])
      showNotif('Backlog item generated by AI!')
      setAiPrompt('')
      setShowAiGenerate(false)
    } catch (err) {
      showNotif(err.message || 'AI generation failed', 'error')
    }
    setGenerating(false)
  }

  const resetForm = () => {
    setForm({ description: '', priority: 'Medium', owner: '', status: 'New', image_data: '', image_name: '' })
    setShowAdd(false)
  }

  const handleAddItem = async (e) => {
    e.preventDefault()
    if (!form.description.trim()) {
      showNotif('Description is required', 'error')
      return
    }
    setSubmitting(true)
    try {
      const created = await api.createBacklogItem({
        description: form.description.trim(),
        priority: form.priority,
        owner: form.owner || null,
        status: form.status,
        image: form.image_data || null,
      })
      setItems(prev => [created, ...prev])
      showNotif('Backlog item added')
      resetForm()
    } catch (err) {
      showNotif(err.message || 'Failed to add backlog item', 'error')
    }
    setSubmitting(false)
  }

  const handleDelete = async (id) => {
    try {
      await api.deleteBacklogItem(id)
      setItems(prev => prev.filter(i => i.id !== id))
      showNotif('Item removed', 'info')
    } catch (err) {
      // If item was already deleted (404), remove from local state gracefully
      if (err.message && err.message.includes('No BacklogItem matches')) {
        setItems(prev => prev.filter(i => i.id !== id))
        showNotif('Item was already removed', 'info')
      } else {
        showNotif(err.message || 'Failed to delete item', 'error')
      }
    }
  }

  const handleStatusChange = async (id, newStatus) => {
    try {
      const updated = await api.updateBacklogItem(id, { status: newStatus })
      setItems(prev => prev.map(i => i.id === id ? { ...i, ...updated } : i))
    } catch (err) {
      showNotif(err.message || 'Failed to update status', 'error')
    }
  }

  const handlePriorityChange = async (id, newPriority) => {
    try {
      const updated = await api.updateBacklogItem(id, { priority: newPriority })
      setItems(prev => prev.map(i => i.id === id ? { ...i, ...updated } : i))
    } catch (err) {
      showNotif(err.message || 'Failed to update priority', 'error')
    }
  }

  const handleOwnerChange = async (id, newOwner) => {
    try {
      const updated = await api.updateBacklogItem(id, { owner: newOwner || null })
      setItems(prev => prev.map(i => i.id === id ? { ...i, ...updated } : i))
    } catch (err) {
      showNotif(err.message || 'Failed to update assignee', 'error')
    }
  }

  const getOwnerName = (owner) => {
    if (!owner) return 'Unassigned'
    const emp = employees.find(e => String(e.id) === String(owner))
    return emp?.name || emp?.email || 'Unassigned'
  }

  const handleConvertToTask = async (backlogItem) => {
    setConvertingId(backlogItem.id)
    try {
      const result = await api.convertBacklogToTask(backlogItem.id)
      if (result.status === 'already_converted') {
        showNotif('Task already created for this item', 'info')
      } else {
        showNotif('Task created automatically from backlog item!', 'success')
      }
      // Refresh the list to show updated task info
      const data = await api.getBacklogItems()
      setItems(Array.isArray(data) ? data : data.results || [])
    } catch (err) {
      showNotif(err.message || 'Failed to convert to task', 'error')
    }
    setConvertingId(null)
  }

  const handleApproveSuggestion = async (sugg) => {
    try {
      // Build a comprehensive description from structured fields
      const descParts = []
      if (sugg.title) descParts.push(`# ${sugg.title}`)
      if (sugg.background) descParts.push(`\n**Background / Problem Statement:**\n${sugg.background}`)
      if (sugg.proposed_enhancement) descParts.push(`\n**Proposed Enhancement:**\n${sugg.proposed_enhancement}`)
      if (sugg.expected_benefits) descParts.push(`\n**Expected Benefits:**\n${sugg.expected_benefits}`)
      if (sugg.stakeholders) descParts.push(`\n**Stakeholders:** ${sugg.stakeholders}`)
      if (sugg.source_of_idea) descParts.push(`\n**Source:** ${sugg.source_of_idea}`)
      if (sugg.meeting_title) descParts.push(`\n**From Meeting:** ${sugg.meeting_title}`)

      const description = descParts.join('\n')

      const created = await api.createBacklogItem({
        description: description || sugg.title,
        priority: sugg.priority || 'Medium',
        status: 'Future Consideration',
        source: 'auto-capture',
        source_ref: sugg.source,
        owner: sugg.owner || null,
      })
      // Refresh items
      const data = await api.getBacklogItems()
      setItems(Array.isArray(data) ? data : data.results || [])
      setSuggestions(prev => prev.filter(s => s.id !== sugg.id))
      showNotif('Enhancement added to backlog!')
    } catch (err) {
      showNotif(err.message || 'Failed to approve suggestion', 'error')
    }
  }

  const dismissSuggestion = (id) => {
    setSuggestions(prev => prev.filter(s => s.id !== id))
  }

  const handleScan = async (autoApprove = false, daysBack = 1) => {
    setScanning(true)
    let found = []
    try {
      const result = await api.scanBacklogKeywords(daysBack)
      if (result.items && result.items.length > 0) {
        const mapped = result.items.map((s, idx) => ({
          id: 'sugg_' + Date.now() + '_' + idx + '_' + Math.random().toString(36).slice(2, 8),
          title: s.title || '',
          background: s.background || '',
          proposed_enhancement: s.proposed_enhancement || '',
          expected_benefits: s.expected_benefits || '',
          stakeholders: s.stakeholders || '',
          priority: s.priority || 'Medium',
          source_of_idea: s.source_of_idea || '',
          source: s.source || 'meeting',
          meeting_title: s.meeting_title || '',
          source_id: s.source_id || null,
          created_at: Date.now(),
          reviewed: false,
        }))
        found = [...found, ...mapped]
      }
    } catch {}

    if (found.length > 0) {
      const existingSources = new Set(
        items.filter(i => i.source_ref).map(i => i.source_ref)
      )
      const existingTitles = new Set(
        items.map(i => i.title?.trim().toLowerCase())
      )
      const newFound = found.filter(s =>
        !existingSources.has(s.source) &&
        !existingTitles.has(s.title.trim().toLowerCase())
      )
      if (autoApprove) {
        let count = 0
        for (const s of newFound) {
          try {
            const created = await api.createBacklogItem({
              description: s.background || s.title,
              priority: s.priority || 'Medium',
              status: 'Future Consideration',
              source: 'auto-capture',
              source_ref: s.source,
            })
            count++
          } catch {}
        }
        if (count > 0) {
          showNotif(`Auto-captured ${count} enhancement item(s)`)
          api.getBacklogItems().then(data => setItems(Array.isArray(data) ? data : data.results || []))
        }
      } else {
        setSuggestions(prev => [...newFound, ...prev])
        showNotif(`Found ${newFound.length} product enhancement candidate(s) — review below`)
      }
    } else {
      showNotif('No enhancement candidates found in discussions', 'info')
    }
    setScanning(false)
  }

  const handleCustomScan = async () => {
    if (!customScanDate) {
      showNotif('Please select a date', 'error')
      return
    }
    const selected = new Date(customScanDate)
    const now = new Date()
    const diffMs = now - selected
    const diffDays = Math.ceil(diffMs / (1000 * 60 * 60 * 24))
    const daysBack = Math.max(diffDays, 1)
    setShowCustomScan(false)
    await handleScan(false, daysBack)
  }

  useEffect(() => { setPage(1) }, [search, priorityFilter, statusFilter, tab])

  // Filter items by tab
  const itemsByTab = items.filter(item => {
    if (tab === 'pending') return !item.task_id && item.status !== 'Done'
    if (tab === 'converted') return item.task_id
    return true
  })

  const filteredItems = itemsByTab
    .filter(item => {
      if (search && !item.description?.toLowerCase().includes(search.toLowerCase())) return false
      if (priorityFilter !== 'All' && item.priority !== priorityFilter) return false
      if (statusFilter !== 'All' && item.status !== statusFilter) return false
      return true
    })
    .sort((a, b) => new Date(b.created_at) - new Date(a.created_at))

  const totalPages = Math.max(1, Math.ceil(filteredItems.length / perPage))
  const currentPage = Math.min(page, totalPages)
  const paginatedItems = filteredItems.slice((currentPage - 1) * perPage, currentPage * perPage)

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="animate-spin w-8 h-8 border-2 border-[var(--color-primary-500)] border-t-transparent rounded-full" />
      </div>
    )
  }

  // ── Pipeline stats ──
  const pendingReviewCount = suggestions.length
  const unconvertedCount = items.filter(i => !i.task_id && i.status !== 'Done').length
  const convertedCount = items.filter(i => i.task_id).length

  return (
    <div className="animate-fade-in space-y-6">
      {notification && (
        <div className={`fixed top-4 right-4 z-50 px-5 py-3 rounded-xl shadow-2xl text-sm font-medium animate-slide-up ${
          notification.type === 'error' ? 'bg-red-600 text-white' : notification.type === 'info' ? 'bg-[var(--color-badge-bg)] text-[var(--color-text-secondary)]' : 'bg-green-600 text-white'
        }`}>
          {notification.message}
        </div>
      )}

      {/* ════════ PIPELINE FLOW HEADER ════════ */}
      <div className="bg-[var(--color-card-bg)] border border-[var(--color-card-border)] rounded-2xl p-6">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-6">
          <div>
            <h1 className="text-2xl font-bold text-[var(--color-text-primary)]">Backlog Pipeline</h1>
            <p className="text-sm text-[var(--color-text-secondary)] mt-1">Meetings → AI Detection → Review & Approve → Auto-create Tasks</p>
          </div>
          <div className="flex items-center gap-3 max-sm:w-full max-sm:flex-col">
            <button
              onClick={() => handleScan(false)}
              disabled={scanning}
              className="flex items-center justify-center gap-2 px-4 py-2 rounded-xl text-sm font-medium bg-[var(--color-badge-bg)] text-[var(--color-text-primary)] hover:bg-[var(--color-card-border)] transition-colors border border-[var(--color-card-border)] disabled:opacity-50 max-sm:w-full"
            >
              <svg className={`w-4 h-4 shrink-0 ${scanning ? 'animate-spin' : ''}`} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
              </svg>
              {scanning ? 'Scanning...' : 'Scan Discussions'}
            </button>
            <button
              onClick={() => setShowCustomScan(true)}
              disabled={scanning}
              className="flex items-center justify-center gap-2 px-4 py-2 rounded-xl text-sm font-medium bg-[var(--color-badge-bg)] text-[var(--color-text-primary)] hover:bg-[var(--color-card-border)] transition-colors border border-[var(--color-card-border)] disabled:opacity-50 max-sm:w-full"
            >
              <svg className="w-4 h-4 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
              </svg>
              Custom Scan
            </button>
            <button
              onClick={() => setShowAiGenerate(true)}
              disabled={generating}
              className="flex items-center justify-center gap-2 px-4 py-2 rounded-xl text-sm font-medium bg-[var(--color-badge-bg)] text-[var(--color-text-primary)] hover:bg-[var(--color-card-border)] transition-colors border border-[var(--color-card-border)] disabled:opacity-50 max-sm:w-full"
            >
              <svg className={`w-4 h-4 shrink-0 ${generating ? 'animate-pulse' : ''}`} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 00-3.09 3.09zM18.259 8.715L18 9.75l-.259-1.035a3.375 3.375 0 00-2.455-2.456L14.25 6l1.036-.259a3.375 3.375 0 002.455-2.456L18 2.25l.259 1.035a3.375 3.375 0 002.455 2.456L21.75 6l-1.036.259a3.375 3.375 0 00-2.455 2.456zM16.894 20.567L16.5 21.75l-.394-1.183a2.25 2.25 0 00-1.423-1.423L13.5 18.75l1.183-.394a2.25 2.25 0 001.423-1.423l.394-1.183.394 1.183a2.25 2.25 0 001.423 1.423l1.183.394-1.183.394a2.25 2.25 0 00-1.423 1.423z" />
              </svg>
              {generating ? 'Generating...' : 'Generate with AI'}
            </button>
            <button
              onClick={() => setShowAdd(true)}
              className="flex items-center justify-center gap-2 px-4 py-2 rounded-xl text-sm font-medium bg-[var(--color-primary-600)] text-white hover:bg-[var(--color-primary-700)] transition-colors shadow-lg shadow-[var(--color-primary-600)]/20 max-sm:w-full"
            >
              <svg className="w-4 h-4 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M12 4v16m8-8H4" />
              </svg>
              Add Item
            </button>
          </div>
        </div>

        {/* ── Pipeline Steps ── */}
        <div className="grid grid-cols-1 sm:grid-cols-4 gap-3">
          <div className="flex items-center gap-3 p-3 rounded-xl bg-[var(--color-badge-bg)] border border-[var(--color-card-border)]">
            <div className="w-10 h-10 rounded-lg bg-yellow-500/20 flex items-center justify-center text-lg shrink-0">🎙️</div>
            <div>
              <p className="text-xs text-[var(--color-text-muted)] font-medium uppercase tracking-wider">Step 1</p>
              <p className="text-sm font-semibold text-[var(--color-text-primary)]">Source Detection</p>
              <p className="text-xs text-[var(--color-text-secondary)]">Meeting Transcripts</p>
            </div>
          </div>
          <div className="flex items-center gap-3 p-3 rounded-xl bg-[var(--color-badge-bg)] border border-[var(--color-card-border)]">
            <div className="w-10 h-10 rounded-lg bg-[var(--color-primary-500)]/20 flex items-center justify-center text-lg shrink-0">🤖</div>
            <div>
              <p className="text-xs text-[var(--color-text-muted)] font-medium uppercase tracking-wider">Step 2</p>
              <p className="text-sm font-semibold text-[var(--color-text-primary)]">AI Detection</p>
              <p className="text-xs text-[var(--color-text-secondary)]">{pendingReviewCount} pending review</p>
            </div>
          </div>
          <div className="flex items-center gap-3 p-3 rounded-xl bg-[var(--color-badge-bg)] border border-[var(--color-card-border)]">
            <div className="w-10 h-10 rounded-lg bg-blue-500/20 flex items-center justify-center text-lg shrink-0">✅</div>
            <div>
              <p className="text-xs text-[var(--color-text-muted)] font-medium uppercase tracking-wider">Step 3</p>
              <p className="text-sm font-semibold text-[var(--color-text-primary)]">Review & Approve</p>
              <p className="text-xs text-[var(--color-text-secondary)]">{unconvertedCount} unconverted</p>
            </div>
          </div>
          <div className="flex items-center gap-3 p-3 rounded-xl bg-[var(--color-badge-bg)] border border-[var(--color-card-border)]">
            <div className="w-10 h-10 rounded-lg bg-green-500/20 flex items-center justify-center text-lg shrink-0">📋</div>
            <div>
              <p className="text-xs text-[var(--color-text-muted)] font-medium uppercase tracking-wider">Step 4</p>
              <p className="text-sm font-semibold text-[var(--color-text-primary)]">Task Created</p>
              <p className="text-xs text-[var(--color-text-secondary)]">{convertedCount} tasks</p>
            </div>
          </div>
        </div>

        {/* ── Arrow connecting the steps ── */}
        <div className="hidden sm:flex items-center justify-between px-4 mt-2">
          {['🎙️ Source', '🤖 AI Detect', '✅ Review', '📋 Task'].map((step, i) => (
            <div key={step} className="flex items-center gap-2">
              <span className="text-xs text-[var(--color-text-muted)]">{step}</span>
              {i < 3 && <span className="text-[var(--color-text-muted)] text-xs">→</span>}
            </div>
          ))}
        </div>
      </div>

      {/* ════════ PENDING REVIEW SECTION — Structured Enhancement Items ════════ */}
      {suggestions.length > 0 && (
        <div className="bg-[var(--color-card-bg)] border border-[var(--color-primary-500)]/20 rounded-2xl overflow-hidden animate-slide-up">
          <div className="flex items-center justify-between px-5 py-4 border-b border-[var(--color-primary-500)]/10">
            <div className="flex items-center gap-2">
              <svg className="w-5 h-5 text-[var(--color-primary-500)]" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 00-3.09 3.09z" />
              </svg>
              <h2 className="text-sm font-semibold text-[var(--color-primary-300)]">Product Enhancements Detected</h2>
              <span className="text-xs bg-[var(--color-primary-500)]/20 text-[var(--color-primary-300)] px-2 py-0.5 rounded-full">{suggestions.length} found</span>
            </div>
            <button
              onClick={() => setSuggestions([])}
              className="text-xs text-[var(--color-text-muted)] hover:text-[var(--color-text-secondary)] transition-colors"
            >
              Dismiss All
            </button>
          </div>
          <div className="divide-y divide-[var(--color-card-border)]">
            {suggestions.map(s => (
              <div key={s.id} className="px-5 py-4 hover:bg-[var(--color-primary-500)]/[0.02] transition-colors">
                <div className="flex flex-col sm:flex-row items-start gap-4">
                  <div className="flex-1 min-w-0 w-full sm:w-auto">
                    {/* Title & Meeting Source */}
                    <div className="flex items-center gap-2 mb-1.5">
                      <span className="text-sm">{sourceIcon(s.source)}</span>
                      <h3 className="text-sm font-semibold text-[var(--color-text-primary)]">{s.title}</h3>
                      <span className={`text-[10px] font-medium px-2 py-0.5 rounded-full border ${PRIORITY_COLORS[s.priority] || PRIORITY_COLORS.Medium}`}>
                        {s.priority}
                      </span>
                    </div>

                    {/* Background */}
                    {s.background && (
                      <div className="mb-1.5">
                        <p className="text-[10px] font-medium text-[var(--color-text-muted)] uppercase tracking-wider mb-0.5">Problem</p>
                        <p className="text-xs text-[var(--color-text-secondary)] leading-relaxed">{s.background}</p>
                      </div>
                    )}

                    {/* Proposed Enhancement */}
                    {s.proposed_enhancement && (
                      <div className="mb-1.5">
                        <p className="text-[10px] font-medium text-[var(--color-text-muted)] uppercase tracking-wider mb-0.5">Proposed Enhancement</p>
                        <p className="text-xs text-[var(--color-text-secondary)] leading-relaxed">{s.proposed_enhancement}</p>
                      </div>
                    )}

                    {/* Expected Benefits */}
                    {s.expected_benefits && (
                      <div className="mb-1.5">
                        <p className="text-[10px] font-medium text-[var(--color-text-muted)] uppercase tracking-wider mb-0.5">Business Impact</p>
                        <p className="text-xs text-[var(--color-text-secondary)] leading-relaxed">{s.expected_benefits}</p>
                      </div>
                    )}

                    {/* Metadata row */}
                    <div className="flex items-center gap-3 mt-2 text-[10px] text-[var(--color-text-muted)]">
                      {s.stakeholders && (
                        <span className="flex items-center gap-1">
                          <svg className="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
                            <path strokeLinecap="round" strokeLinejoin="round" d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0z" />
                          </svg>
                          {s.stakeholders}
                        </span>
                      )}
                      {s.source_of_idea && (
                        <span className="flex items-center gap-1">
                          <svg className="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
                            <path strokeLinecap="round" strokeLinejoin="round" d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
                          </svg>
                          {s.source_of_idea}
                        </span>
                      )}
                      {s.meeting_title && (
                        <span className="flex items-center gap-1">
                          <svg className="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
                            <path strokeLinecap="round" strokeLinejoin="round" d="M19 20H5a2 2 0 01-2-2V6a2 2 0 012-2h10a2 2 0 012 2v1m2 13a2 2 0 01-2-2V7m2 13a2 2 0 002-2V9a2 2 0 00-2-2h-2m-4-3H9M7 16h6M7 8h6v4H7V8z" />
                          </svg>
                          {s.meeting_title}
                        </span>
                      )}
                    </div>
                  </div>

                  {/* Action buttons */}
                  <div className="flex items-center gap-2 shrink-0 self-end sm:self-auto">
                    <button
                      onClick={() => handleApproveSuggestion(s)}
                      className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium bg-green-600/20 text-green-300 hover:bg-green-600/30 transition-colors border border-green-500/20"
                    >
                      <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                        <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                      </svg>
                      Add to Backlog
                    </button>
                    <button
                      onClick={() => dismissSuggestion(s.id)}
                      className="px-3 py-1.5 rounded-lg text-xs font-medium bg-gray-500/20 text-gray-400 hover:bg-gray-500/30 transition-colors border border-gray-500/20"
                    >
                      Dismiss
                    </button>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* ════════ TABS & FILTERS ════════ */}
      <div className="flex flex-col sm:flex-row gap-3">
        <div className="flex items-center gap-1 p-1 rounded-xl bg-[var(--color-badge-bg)] border border-[var(--color-card-border)]">
          {[
            { key: 'all', label: 'All Items', count: items.length },
            { key: 'pending', label: 'Unconverted', count: unconvertedCount },
            { key: 'converted', label: 'Tasks', count: convertedCount },
          ].map(t => (
            <button
              key={t.key}
              onClick={() => setTab(t.key)}
              className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-all ${
                tab === t.key
                  ? 'bg-[var(--color-primary-600)] text-white shadow-sm'
                  : 'text-[var(--color-text-secondary)] hover:text-[var(--color-text-primary)]'
              }`}
            >
              {t.label}
              <span className={`ml-1.5 px-1.5 py-0.5 rounded text-[10px] ${
                tab === t.key ? 'bg-white/15' : 'bg-[var(--color-card-border)]'
              }`}>
                {t.count}
              </span>
            </button>
          ))}
        </div>
      </div>

      <div className="flex flex-col sm:flex-row gap-3">
        <div className="relative flex-1">
          <svg className="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-[var(--color-text-muted)] pointer-events-none" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
          </svg>
          <input
            type="text"
            placeholder="Search backlog..."
            value={search}
            onChange={e => setSearch(e.target.value)}
            className="w-full pl-10 pr-4 py-2.5 rounded-xl text-sm bg-[var(--color-badge-bg)] text-[var(--color-text-primary)] border border-[var(--color-card-border)] placeholder-[var(--color-text-muted)] focus:outline-none focus:ring-2 focus:ring-[var(--color-primary-500)]/40 transition-all"
          />
        </div>
        <select
          value={priorityFilter}
          onChange={e => setPriorityFilter(e.target.value)}
          className="px-4 py-2.5 rounded-xl text-sm bg-[var(--color-badge-bg)] text-[var(--color-text-primary)] border border-[var(--color-card-border)] focus:outline-none focus:ring-2 focus:ring-[var(--color-primary-500)]/40 transition-all cursor-pointer"
        >
          {PRIORITIES.map(p => (
            <option key={p} value={p}>{p === 'All' ? 'All Priorities' : p}</option>
          ))}
        </select>
        <select
          value={statusFilter}
          onChange={e => setStatusFilter(e.target.value)}
          className="px-4 py-2.5 rounded-xl text-sm bg-[var(--color-badge-bg)] text-[var(--color-text-primary)] border border-[var(--color-card-border)] focus:outline-none focus:ring-2 focus:ring-[var(--color-primary-500)]/40 transition-all cursor-pointer"
        >
          <option value="All">All Statuses</option>
          {STATUSES.map(s => (
            <option key={s} value={s}>{s}</option>
          ))}
        </select>
      </div>

      <div className="flex items-center justify-between text-sm text-[var(--color-text-secondary)]">
        <span>{filteredItems.length} item{filteredItems.length !== 1 ? 's' : ''}{filteredItems.length > perPage ? ` — Page ${currentPage} of ${totalPages}` : ''}</span>
      </div>

      {/* ════════ BACKLOG ITEMS LIST ════════ */}
      {paginatedItems.length === 0 ? (
        <div className="flex flex-col items-center justify-center py-20 text-center">
          <svg className="w-16 h-16 text-[var(--color-text-muted)] mb-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10" />
          </svg>
          <p className="text-lg font-medium text-[var(--color-text-secondary)]">
            {tab === 'pending' ? 'All items converted to tasks!' : tab === 'converted' ? 'No converted items yet' : 'No backlog items yet'}
          </p>
          <p className="text-sm text-[var(--color-text-muted)] mt-1 mb-4">
            {tab === 'pending'
              ? 'All backlog items have been converted to tasks. Great work!'
              : tab === 'converted'
              ? 'Items approved from the review panel will appear here as tasks.'
              : 'Add your first item or scan discussions to capture backlog ideas'}
          </p>
          {tab === 'all' && (
            <button
              onClick={() => setShowAdd(true)}
              className="flex items-center gap-2 px-4 py-2 rounded-xl text-sm font-medium bg-[var(--color-primary-600)] text-white hover:bg-[var(--color-primary-700)] transition-colors"
            >
              <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M12 4v16m8-8H4" />
              </svg>
              Add First Item
            </button>
          )}
        </div>
      ) : (
        <>
        <div className="grid gap-3">
          {paginatedItems.map(item => (
            <div
              key={item.id}
              className="bg-[var(--color-card-bg)] border border-[var(--color-card-border)] rounded-2xl p-5 hover:border-[var(--color-primary-500)]/20 transition-all duration-200 animate-slide-up"
            >
              <div className="flex flex-col sm:flex-row items-start gap-4">
                <div className="flex-1 min-w-0 w-full sm:w-auto">
                  <div className="flex items-center gap-3 flex-wrap mb-2">
                    <span className={`text-xs font-medium px-2.5 py-0.5 rounded-full border ${PRIORITY_COLORS[item.priority] || PRIORITY_COLORS.Medium}`}>
                      {item.priority}
                    </span>
                    <span className={`text-xs font-medium px-2.5 py-0.5 rounded-full border ${STATUS_COLORS[item.status] || STATUS_COLORS.New}`}>
                      {item.status}
                    </span>
                    {item.source === 'auto-capture' && (
                      <span className="text-xs font-medium px-2.5 py-0.5 rounded-full border border-purple-500/30 bg-purple-500/20 text-purple-300">
                        Auto-captured
                      </span>
                    )}
                    {item.task_id ? (
                      <span className="flex items-center gap-1 text-xs font-medium px-2.5 py-0.5 rounded-full border border-green-500/30 bg-green-500/20 text-green-300">
                        <svg className="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                          <path strokeLinecap="round" strokeLinejoin="round" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
                        </svg>
                        Task #{item.task_id}
                      </span>
                    ) : (
                      <span className="text-xs font-medium px-2.5 py-0.5 rounded-full border border-gray-500/30 bg-gray-500/20 text-gray-400">
                        No task
                      </span>
                    )}
                  </div>
                  <p className="text-sm text-[var(--color-text-primary)] leading-relaxed cursor-pointer hover:text-[var(--color-primary-400)] transition-colors" onClick={() => setDetailItem(item)}>{item.description}</p>
                  <div className="flex items-center gap-4 mt-2 text-xs text-[var(--color-text-muted)]">
                    <span className="flex items-center gap-1">
                      <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
                        <path strokeLinecap="round" strokeLinejoin="round" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                      </svg>
                      {getOwnerName(item.owner)}
                    </span>
                    <span className="flex items-center gap-1">
                      <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
                        <path strokeLinecap="round" strokeLinejoin="round" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
                      </svg>
                      {formatDate(item.created_at)}
                    </span>
                    {item.source_ref && (
                      <span className="flex items-center gap-1">
                        <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
                          <path strokeLinecap="round" strokeLinejoin="round" d="M7 8h10M7 12h4m1 8l-4-4H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-3l-4 4z" />
                        </svg>
                        {item.source_ref}
                      </span>
                    )}
                  </div>
                  {item.task_id && (
                    <div className="mt-2 flex items-center gap-2 text-xs bg-green-500/10 rounded-lg px-3 py-1.5 border border-green-500/20 w-fit">
                      <svg className="w-3.5 h-3.5 text-green-400 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                        <path strokeLinecap="round" strokeLinejoin="round" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
                      </svg>
                      <span className="text-green-300">Task <span className="font-semibold">#{item.task_id}</span> created</span>
                      <span className={`text-xs px-1.5 py-0.5 rounded ${
                        item.task_status === 'completed' ? 'bg-green-500/20 text-green-300' :
                        item.task_status === 'in_progress' ? 'bg-blue-500/20 text-blue-300' :
                        'bg-yellow-500/20 text-yellow-300'
                      }`}>
                        {item.task_status?.replace('_', ' ')}
                      </span>
                      <a href={`/tasks?task=${item.task_id}`} className="text-[var(--color-primary-400)] hover:text-[var(--color-primary-300)] underline ml-1">
                        View in Tasks
                      </a>
                    </div>
                  )}
                  {item.image && (
                    <div className="mt-3">
                      <img
                        src={item.image}
                        alt="Attachment"
                        className="max-h-32 rounded-lg object-cover border border-[var(--color-card-border)] cursor-pointer"
                        onClick={() => setSelectedImage(selectedImage === item.id ? null : item.id)}
                      />
                    </div>
                  )}
                  {selectedImage === item.id && item.image && (
                    <div className="fixed inset-0 z-50 bg-black/70 flex items-center justify-center p-4" onClick={() => setSelectedImage(null)}>
                      <img src={item.image} alt="" className="max-w-full max-h-full rounded-2xl" />
                    </div>
                  )}
                </div>
                <div className="flex sm:flex-col gap-2 shrink-0 w-full sm:w-auto sm:min-w-[130px]">
                  <div className="flex sm:flex-col gap-2 w-full">
                    <div className="relative flex-1 sm:flex-none">
                      <select
                        value={item.status}
                        onChange={e => handleStatusChange(item.id, e.target.value)}
                        className="appearance-none w-full px-3 py-1.5 rounded-lg text-xs font-medium bg-[var(--color-badge-bg)] text-[var(--color-text-primary)] border border-[var(--color-card-border)] cursor-pointer pr-7 focus:outline-none focus:ring-2 focus:ring-[var(--color-primary-500)]/40"
                      >
                        {STATUSES.map(s => (
                          <option key={s} value={s}>{s}</option>
                        ))}
                      </select>
                      <svg className="absolute right-2 top-1/2 -translate-y-1/2 w-3 h-3 text-[var(--color-text-muted)] pointer-events-none" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                        <path strokeLinecap="round" strokeLinejoin="round" d="M19 9l-7 7-7-7" />
                      </svg>
                    </div>
                    <div className="relative flex-1 sm:flex-none">
                      <select
                        value={item.priority}
                        onChange={e => handlePriorityChange(item.id, e.target.value)}
                        className="appearance-none w-full px-3 py-1.5 rounded-lg text-xs font-medium bg-[var(--color-badge-bg)] text-[var(--color-text-primary)] border border-[var(--color-card-border)] cursor-pointer pr-7 focus:outline-none focus:ring-2 focus:ring-[var(--color-primary-500)]/40"
                      >
                        {PRIORITIES.filter(p => p !== 'All').map(p => (
                          <option key={p} value={p}>{p}</option>
                        ))}
                      </select>
                      <svg className="absolute right-2 top-1/2 -translate-y-1/2 w-3 h-3 text-[var(--color-text-muted)] pointer-events-none" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                        <path strokeLinecap="round" strokeLinejoin="round" d="M19 9l-7 7-7-7" />
                      </svg>
                    </div>
                    <div className="relative flex-1 sm:flex-none">
                      <select
                        value={item.owner || ''}
                        onChange={e => handleOwnerChange(item.id, e.target.value)}
                        className="appearance-none w-full px-3 py-1.5 rounded-lg text-xs font-medium bg-[var(--color-badge-bg)] text-[var(--color-text-primary)] border border-[var(--color-card-border)] cursor-pointer pr-7 focus:outline-none focus:ring-2 focus:ring-[var(--color-primary-500)]/40"
                      >
                        <option value="">Unassigned</option>
                        {employees.map(emp => (
                          <option key={emp.id} value={emp.id}>{emp.name || emp.email}</option>
                        ))}
                      </select>
                      <svg className="absolute right-2 top-1/2 -translate-y-1/2 w-3 h-3 text-[var(--color-text-muted)] pointer-events-none" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                        <path strokeLinecap="round" strokeLinejoin="round" d="M19 9l-7 7-7-7" />
                      </svg>
                    </div>
                  </div>

                  {/* ── Convert to Task button ── */}
                  {!item.task_id && (
                    <button
                      onClick={() => handleConvertToTask(item)}
                      disabled={convertingId === item.id}
                      className="flex items-center justify-center gap-1.5 px-3 py-2 rounded-lg text-xs font-medium bg-green-600/20 text-green-300 hover:bg-green-600/30 transition-colors border border-green-500/20 disabled:opacity-50 w-full"
                    >
                      {convertingId === item.id ? (
                        <svg className="w-3.5 h-3.5 animate-spin" fill="none" viewBox="0 0 24 24">
                          <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                          <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                        </svg>
                      ) : (
                        <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                          <path strokeLinecap="round" strokeLinejoin="round" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
                        </svg>
                      )}
                      {convertingId === item.id ? 'Converting...' : 'Create Task'}
                    </button>
                  )}

                  {/* ── Delete ── */}
                  <button
                    onClick={() => handleDelete(item.id)}
                    className="flex items-center justify-center gap-1.5 px-3 py-2 rounded-lg text-xs font-medium bg-red-500/10 text-red-400 hover:bg-red-500/20 transition-colors border border-red-500/20 w-full"
                  >
                    <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                      <path strokeLinecap="round" strokeLinejoin="round" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                    </svg>
                    Delete
                  </button>
                </div>
              </div>
            </div>
          ))}
        </div>

        {totalPages > 1 && (
          <div className="flex flex-col sm:flex-row items-center justify-between pt-2 gap-3">
            <p className="text-xs text-[var(--color-text-muted)]">
              Showing {(currentPage - 1) * perPage + 1}–{Math.min(currentPage * perPage, filteredItems.length)} of {filteredItems.length}
            </p>
            <div className="flex items-center gap-1">
              <button
                onClick={() => setPage(currentPage - 1)}
                disabled={currentPage <= 1}
                className={`p-2 rounded-lg text-sm transition-all ${currentPage <= 1 ? 'text-[var(--color-text-muted)] cursor-not-allowed' : 'text-[var(--color-text-secondary)] hover:bg-[var(--color-badge-bg)]'}`}
              >
                <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M15 19l-7-7 7-7" />
                </svg>
              </button>
              {Array.from({ length: totalPages }, (_, i) => i + 1).map(p => (
                <button
                  key={p}
                  onClick={() => setPage(p)}
                  className={`w-8 h-8 rounded-lg text-xs font-medium transition-all ${p === currentPage ? 'bg-[var(--color-primary-600)] text-white' : 'text-[var(--color-text-secondary)] hover:bg-[var(--color-badge-bg)]'}`}
                >
                  {p}
                </button>
              ))}
              <button
                onClick={() => setPage(currentPage + 1)}
                disabled={currentPage >= totalPages}
                className={`p-2 rounded-lg text-sm transition-all ${currentPage >= totalPages ? 'text-[var(--color-text-muted)] cursor-not-allowed' : 'text-[var(--color-text-secondary)] hover:bg-[var(--color-badge-bg)]'}`}
              >
                <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M9 5l7 7-7 7" />
                </svg>
              </button>
            </div>
          </div>
        )}
        </>
      )}

      {/* ════════ AI GENERATE MODAL ════════ */}
      {showAiGenerate && createPortal(
        <div className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center p-4" onClick={() => { setShowAiGenerate(false); setAiPrompt('') }}>
          <div className="bg-[var(--color-card-bg)] border border-[var(--color-card-border)] rounded-2xl w-full max-w-lg shadow-2xl animate-scale-in" onClick={e => e.stopPropagation()}>
            <div className="flex items-center justify-between p-5 border-b border-[var(--color-card-border)]">
              <div className="flex items-center gap-3">
                <div className="w-9 h-9 rounded-lg bg-[var(--color-primary-500)]/20 flex items-center justify-center">
                  <svg className="w-5 h-5 text-[var(--color-primary-500)]" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 00-3.09 3.09zM18.259 8.715L18 9.75l-.259-1.035a3.375 3.375 0 00-2.455-2.456L14.25 6l1.036-.259a3.375 3.375 0 002.455-2.456L18 2.25l.259 1.035a3.375 3.375 0 002.455 2.456L21.75 6l-1.036.259a3.375 3.375 0 00-2.455 2.456zM16.894 20.567L16.5 21.75l-.394-1.183a2.25 2.25 0 00-1.423-1.423L13.5 18.75l1.183-.394a2.25 2.25 0 001.423-1.423l.394-1.183.394 1.183a2.25 2.25 0 001.423 1.423l1.183.394-1.183.394a2.25 2.25 0 00-1.423 1.423z" />
                  </svg>
                </div>
                <div>
                  <h2 className="text-lg font-semibold text-[var(--color-text-primary)]">Generate with AI</h2>
                  <p className="text-xs text-[var(--color-text-secondary)]">Describe what needs to be done — AI will structure it</p>
                </div>
              </div>
              <button onClick={() => { setShowAiGenerate(false); setAiPrompt('') }} className="p-1.5 rounded-lg hover:bg-[var(--color-badge-bg)] text-[var(--color-text-muted)] transition-colors">
                <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>
            <div className="p-5 space-y-4">
              <div>
                <label className="block text-sm font-medium text-[var(--color-text-secondary)] mb-1.5">Your Prompt *</label>
                <textarea
                  value={aiPrompt}
                  onChange={e => setAiPrompt(e.target.value)}
                  rows={5}
                  placeholder="e.g. We need a user authentication system with Google OAuth, JWT tokens, and password reset functionality. Assign to Sekar with high priority."
                  className="w-full px-4 py-2.5 rounded-xl text-sm bg-[var(--color-badge-bg)] text-[var(--color-text-primary)] border border-[var(--color-card-border)] placeholder-[var(--color-text-muted)] focus:outline-none focus:ring-2 focus:ring-[var(--color-primary-500)]/40 transition-all resize-none"
                  required
                />
              </div>
              <div className="bg-[var(--color-badge-bg)] rounded-xl p-3 border border-[var(--color-card-border)]">
                <p className="text-xs text-[var(--color-text-secondary)] leading-relaxed">
                  <span className="text-[var(--color-primary-400)] font-medium">💡 Tip:</span> Be specific about what needs to be built, who should do it, and the priority. The AI will generate a well-structured backlog item from your description.
                </p>
              </div>
              <div className="flex items-center gap-3 pt-1">
                <button
                  onClick={handleAiGenerate}
                  disabled={generating}
                  className="flex-1 flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl text-sm font-medium bg-[var(--color-primary-600)] text-white hover:bg-[var(--color-primary-700)] transition-colors shadow-lg shadow-[var(--color-primary-600)]/20 disabled:opacity-50"
                >
                  {generating ? (
                    <>
                      <svg className="w-4 h-4 animate-spin" fill="none" viewBox="0 0 24 24">
                        <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                        <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                      </svg>
                      Generating...
                    </>
                  ) : (
                    <>
                      <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                        <path strokeLinecap="round" strokeLinejoin="round" d="M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 00-3.09 3.09z" />
                      </svg>
                      Generate Backlog Item
                    </>
                  )}
                </button>
                <button
                  onClick={() => { setShowAiGenerate(false); setAiPrompt('') }}
                  className="px-4 py-2.5 rounded-xl text-sm font-medium bg-[var(--color-badge-bg)] text-[var(--color-text-primary)] hover:bg-[var(--color-card-border)] transition-colors border border-[var(--color-card-border)]"
                >
                  Cancel
                </button>
              </div>
            </div>
          </div>
        </div>,
        document.getElementById('portal-root')
      )}

      {/* ════════ ADD ITEM MODAL ════════ */}
      {showAdd && createPortal(
        <div className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center p-4" onClick={resetForm}>
          <div className="bg-[var(--color-card-bg)] border border-[var(--color-card-border)] rounded-2xl w-full max-w-lg max-h-[90vh] overflow-y-auto shadow-2xl animate-scale-in" onClick={e => e.stopPropagation()}>
            <div className="flex items-center justify-between p-5 border-b border-[var(--color-card-border)]">
              <h2 className="text-lg font-semibold text-[var(--color-text-primary)]">Add Backlog Item</h2>
              <button onClick={resetForm} className="p-1.5 rounded-lg hover:bg-[var(--color-badge-bg)] text-[var(--color-text-muted)] transition-colors">
                <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>
            <form onSubmit={handleAddItem} className="p-5 space-y-4">
              <div>
                <label className="block text-sm font-medium text-[var(--color-text-secondary)] mb-1.5">Description *</label>
                <textarea
                  value={form.description}
                  onChange={e => setForm(prev => ({ ...prev, description: e.target.value }))}
                  rows={4}
                  placeholder="Describe the backlog item..."
                  className="w-full px-4 py-2.5 rounded-xl text-sm bg-[var(--color-badge-bg)] text-[var(--color-text-primary)] border border-[var(--color-card-border)] placeholder-[var(--color-text-muted)] focus:outline-none focus:ring-2 focus:ring-[var(--color-primary-500)]/40 transition-all resize-none"
                  required
                />
              </div>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-[var(--color-text-secondary)] mb-1.5">Priority</label>
                  <select
                    value={form.priority}
                    onChange={e => setForm(prev => ({ ...prev, priority: e.target.value }))}
                    className="w-full px-4 py-2.5 rounded-xl text-sm bg-[var(--color-badge-bg)] text-[var(--color-text-primary)] border border-[var(--color-card-border)] focus:outline-none focus:ring-2 focus:ring-[var(--color-primary-500)]/40 transition-all cursor-pointer"
                  >
                    {PRIORITIES.filter(p => p !== 'All').map(p => (
                      <option key={p} value={p}>{p}</option>
                    ))}
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-medium text-[var(--color-text-secondary)] mb-1.5">Status</label>
                  <select
                    value={form.status}
                    onChange={e => setForm(prev => ({ ...prev, status: e.target.value }))}
                    className="w-full px-4 py-2.5 rounded-xl text-sm bg-[var(--color-badge-bg)] text-[var(--color-text-primary)] border border-[var(--color-card-border)] focus:outline-none focus:ring-2 focus:ring-[var(--color-primary-500)]/40 transition-all cursor-pointer"
                  >
                    {STATUSES.map(s => (
                      <option key={s} value={s}>{s}</option>
                    ))}
                  </select>
                </div>
              </div>
              <div>
                <label className="block text-sm font-medium text-[var(--color-text-secondary)] mb-1.5">Assign To</label>
                  <select
                    value={form.owner}
                    onChange={e => setForm(prev => ({ ...prev, owner: e.target.value }))}
                  className="w-full px-4 py-2.5 rounded-xl text-sm bg-[var(--color-badge-bg)] text-[var(--color-text-primary)] border border-[var(--color-card-border)] focus:outline-none focus:ring-2 focus:ring-[var(--color-primary-500)]/40 transition-all cursor-pointer"
                >
                  <option value="">Unassigned</option>
                  {employees.map(emp => (
                    <option key={emp.id} value={emp.id}>{emp.name || emp.email}</option>
                  ))}
                </select>
              </div>
              <div>
                <label className="block text-sm font-medium text-[var(--color-text-secondary)] mb-1.5">Image Attachment</label>
                <div
                  onClick={() => fileInputRef.current?.click()}
                  className="w-full px-4 py-3 rounded-xl text-sm bg-[var(--color-badge-bg)] border border-dashed border-[var(--color-card-border)] text-[var(--color-text-muted)] hover:border-[var(--color-primary-500)]/40 hover:text-[var(--color-text-secondary)] transition-all cursor-pointer flex items-center gap-2"
                >
                  <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
                  </svg>
                  {form.image_name ? form.image_name : 'Click to upload image (max 5MB)'}
                </div>
                <input ref={fileInputRef} type="file" accept="image/*" onChange={handleImageSelect} className="hidden" />
                {form.image_data && (
                  <div className="mt-2 relative inline-block">
                    <img src={form.image_data} alt="Preview" className="h-20 rounded-lg object-cover border border-[var(--color-card-border)]" />
                    <button
                      type="button"
                      onClick={() => setForm(prev => ({ ...prev, image_data: '', image_name: '' }))}
                      className="absolute -top-2 -right-2 p-0.5 rounded-full bg-red-600 text-white hover:bg-red-700 transition-colors"
                    >
                      <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                        <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
                      </svg>
                    </button>
                  </div>
                )}
              </div>
              <div className="flex items-center gap-3 pt-2">
                <button
                  type="submit"
                  disabled={submitting}
                  className="flex-1 px-4 py-2.5 rounded-xl text-sm font-medium bg-[var(--color-primary-600)] text-white hover:bg-[var(--color-primary-700)] transition-colors shadow-lg shadow-[var(--color-primary-600)]/20 disabled:opacity-50"
                >
                  {submitting ? 'Adding...' : 'Add to Backlog'}
                </button>
                <button
                  type="button"
                  onClick={resetForm}
                  className="px-4 py-2.5 rounded-xl text-sm font-medium bg-[var(--color-badge-bg)] text-[var(--color-text-primary)] hover:bg-[var(--color-card-border)] transition-colors border border-[var(--color-card-border)]"
                >
                  Cancel
                </button>
              </div>
            </form>
          </div>
        </div>,
        document.getElementById('portal-root')
      )}

      {/* ════════ DETAIL MODAL ════════ */}
      {detailItem && createPortal(
        <div className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center p-4" onClick={() => setDetailItem(null)}>
          <div className="bg-[var(--color-card-bg)] rounded-2xl shadow-2xl w-full max-w-2xl max-h-[90vh] overflow-y-auto" onClick={e => e.stopPropagation()}>
            <div className="flex items-center justify-between p-5 border-b border-[var(--color-card-border)]">
              <h2 className="text-lg font-semibold text-[var(--color-text-primary)]">Backlog Details</h2>
              <button onClick={() => setDetailItem(null)} className="p-1.5 rounded-lg hover:bg-[var(--color-badge-bg)] text-[var(--color-text-muted)] transition-colors">
                <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>
            <div className="p-5 space-y-4">
              <div className="flex items-center gap-3 flex-wrap">
                <span className={`text-xs font-medium px-2.5 py-0.5 rounded-full border ${PRIORITY_COLORS[detailItem.priority] || PRIORITY_COLORS.Medium}`}>
                  {detailItem.priority}
                </span>
                <span className={`text-xs font-medium px-2.5 py-0.5 rounded-full border ${STATUS_COLORS[detailItem.status] || STATUS_COLORS.New}`}>
                  {detailItem.status}
                </span>
                {detailItem.source === 'auto-capture' && (
                  <span className="text-xs font-medium px-2.5 py-0.5 rounded-full border border-purple-500/30 bg-purple-500/20 text-purple-300">
                    Auto-captured
                  </span>
                )}
                {detailItem.task_id && (
                  <span className="flex items-center gap-1 text-xs font-medium px-2.5 py-0.5 rounded-full border border-green-500/30 bg-green-500/20 text-green-300">
                    <svg className="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                      <path strokeLinecap="round" strokeLinejoin="round" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
                    </svg>
                    Task #{detailItem.task_id}
                  </span>
                )}
              </div>
              <div>
                <label className="block text-sm font-medium text-[var(--color-text-secondary)] mb-1">Description</label>
                <p className="text-sm text-[var(--color-text-primary)] leading-relaxed whitespace-pre-wrap">{detailItem.description}</p>
              </div>
              <div className="grid grid-cols-2 gap-4 text-sm">
                <div>
                  <label className="block text-xs font-medium text-[var(--color-text-muted)] mb-1">Assignee</label>
                  <p className="text-[var(--color-text-primary)]">{getOwnerName(detailItem.owner)}</p>
                </div>
                <div>
                  <label className="block text-xs font-medium text-[var(--color-text-muted)] mb-1">Created</label>
                  <p className="text-[var(--color-text-primary)]">{formatDate(detailItem.created_at)}</p>
                </div>
                {detailItem.source_ref && (
                  <>
                    <div className="col-span-2">
                      <label className="block text-xs font-medium text-[var(--color-text-muted)] mb-1">Source</label>
                      <p className="text-[var(--color-text-primary)]">{detailItem.source_ref}</p>
                    </div>
                  </>
                )}
                {detailItem.task_id && (
                  <div className="col-span-2">
                    <label className="block text-xs font-medium text-[var(--color-text-muted)] mb-1">Linked Task</label>
                    <p className="text-[var(--color-text-primary)]">
                      Task #{detailItem.task_id} — {detailItem.task_title || ''}
                      <span className={`ml-2 text-xs px-1.5 py-0.5 rounded ${
                        detailItem.task_status === 'completed' ? 'bg-green-500/20 text-green-300' :
                        detailItem.task_status === 'in_progress' ? 'bg-blue-500/20 text-blue-300' :
                        'bg-yellow-500/20 text-yellow-300'
                      }`}>
                        {detailItem.task_status?.replace('_', ' ')}
                      </span>
                    </p>
                  </div>
                )}
              </div>
              {detailItem.image && (
                <div>
                  <label className="block text-sm font-medium text-[var(--color-text-secondary)] mb-1">Attachment</label>
                  <img src={detailItem.image} alt="" className="max-h-48 rounded-lg object-cover border border-[var(--color-card-border)]" />
                </div>
              )}
            </div>
          </div>
        </div>,
        document.getElementById('portal-root')
      )}

      {/* ════════ CUSTOM SCAN MODAL ════════ */}
      {showCustomScan && (
        <div className="fixed inset-0 z-50 bg-black/60 flex items-center justify-center p-4" onClick={() => setShowCustomScan(false)}>
          <div className="bg-[var(--color-card-bg)] border border-[var(--color-card-border)] rounded-2xl w-full max-w-sm shadow-2xl animate-scale-in" onClick={e => e.stopPropagation()}>
            <div className="flex items-center justify-between p-5 border-b border-[var(--color-card-border)]">
              <h2 className="text-lg font-semibold text-[var(--color-text-primary)]">Custom Scan</h2>
              <button onClick={() => setShowCustomScan(false)} className="p-1.5 rounded-lg hover:bg-[var(--color-badge-bg)] text-[var(--color-text-muted)] transition-colors">
                <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>
            <div className="p-5 space-y-4">
              <p className="text-sm text-[var(--color-text-secondary)]">Select a date to scan meetings from that day forward.</p>
              <input
                type="date"
                value={customScanDate}
                onChange={e => setCustomScanDate(e.target.value)}
                className="w-full px-4 py-2.5 rounded-xl text-sm bg-[var(--color-badge-bg)] text-[var(--color-text-primary)] border border-[var(--color-card-border)] focus:outline-none focus:ring-2 focus:ring-[var(--color-primary-500)]/40 transition-all"
              />
              <button
                onClick={handleCustomScan}
                disabled={scanning}
                className="w-full flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl text-sm font-medium bg-[var(--color-primary-600)] text-white hover:bg-[var(--color-primary-700)] transition-colors disabled:opacity-50"
              >
                <svg className={`w-4 h-4 ${scanning ? 'animate-spin' : ''}`} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
                </svg>
                {scanning ? 'Scanning...' : 'Scan from this date'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
